/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BottomSearchBar: typeof import('./components/BottomSearchBar.vue')['default']
    ChatBox: typeof import('./components/ChatBox.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    Fileset: typeof import('./components/Fileset.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LogoBar: typeof import('./components/LogoBar.vue')['default']
    ReferencedDocument: typeof import('./components/ReferencedDocument.vue')['default']
    ReferencedDocuments: typeof import('./components/ReferencedDocuments.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SuggesstionsBox: typeof import('./components/SuggesstionsBox.vue')['default']
    Suggestion: typeof import('./components/Suggestion.vue')['default']
    SuggestionsBox: typeof import('./components/SuggestionsBox.vue')['default']
    Suggesttion: typeof import('./components/Suggesttion.vue')['default']
    UploadedFile: typeof import('./components/UploadedFile.vue')['default']
    Visualization: typeof import('./components/Visualization.vue')['default']
  }
}
